_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": darwin-arm64
K_ca3:
    value: 18
K_lat:
    value: 22
alpha:
    value: 0.7315260985795358
beta:
    value: 34
