wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725123339
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.17.8
      8:
      - 4
      - 5
      13: darwin-arm64
K_ca3:
  desc: null
  value: 2
K_lat:
  desc: null
  value: 16
alpha:
  desc: null
  value: 0.904120784289584
beta:
  desc: null
  value: 91
