_wandb:
    value:
        cli_version: 0.26.1
        e:
            ychu4ib5yiwjucaw9o6wupjzanhighgx:
                args:
                    - --sweep-id
                    - ikiru-university-of-oslo/kam_2/g09t3vkj
                    - --count
                    - "96"
                codePath: src/optim_wb/param_search.py
                codePathLocal: param_search.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "32935567360"
                        used: "22210482176"
                email: krubeal.danieli@ibv.uio.no
                executable: /home/doki/main_lab/envs/kamc/bin/python3
                git:
                    commit: aa2275543b541cc79b62c5e2284f6d3566c92432
                    remote: git@github.com:iKiru-hub/KAMemory.git
                host: debian
                memory:
                    total: "33407053824"
                os: Linux-6.12.57+deb13-amd64-x86_64-with-glibc2.41
                program: /home/doki/main_lab/KAMemory/src/optim_wb/param_search.py
                python: CPython 3.13.5
                root: /home/doki/main_lab/KAMemory/src/optim_wb
                startedAt: "2026-04-27T17:13:36.440588Z"
                writerId: ychu4ib5yiwjucaw9o6wupjzanhighgx
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.13.5
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
alpha:
    value: 0.9361703226191854
beta_ca1:
    value: 142.83627080441158
beta_ca3:
    value: 178.19613102468438
beta_eo:
    value: 4.442081464181635
beta_is:
    value: 170.38693018832146
