_wandb:
    value:
        cli_version: 0.26.1
        e:
            c49e1gwht613hzdjw26fpic7g7tv49nt:
                args:
                    - --sweep-id
                    - ikiru-university-of-oslo/kam_2/10qsxyci
                    - --count
                    - "128"
                codePath: src/optim_wb/param_search.py
                codePathLocal: param_search.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "32935567360"
                        used: "22211207168"
                email: krubeal.danieli@ibv.uio.no
                executable: /home/doki/main_lab/envs/kamc/bin/python3
                git:
                    commit: aa2275543b541cc79b62c5e2284f6d3566c92432
                    remote: git@github.com:iKiru-hub/KAMemory.git
                host: debian
                memory:
                    total: "33407053824"
                os: Linux-6.12.57+deb13-amd64-x86_64-with-glibc2.41
                program: /home/doki/main_lab/KAMemory/src/optim_wb/param_search.py
                python: CPython 3.13.5
                root: /home/doki/main_lab/KAMemory/src/optim_wb
                startedAt: "2026-04-27T18:59:45.861755Z"
                writerId: c49e1gwht613hzdjw26fpic7g7tv49nt
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.13.5
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
K_ca3:
    value: 24
K_lat:
    value: 8
alpha:
    value: 0.025023817132440285
beta_ca1:
    value: 11.769053981603816
beta_ca3:
    value: 1.391681362060826
beta_eo:
    value: 220.88588784281464
beta_is:
    value: 12.698668553608885
